import "./globals.css";
import type { Metadata } from "next";
import { Tenor_Sans } from "next/font/google";
import { Bodoni_Moda } from "next/font/google";
import { HeaderComponent } from "@/components/header";
import { FooterComponent } from "@/components/footer";
import { ToasterContext } from "@/context/toasterContext";
import { ProviderNextAuth } from "@/providers/providerNextAuth";
import ReactQueryProvider from "@/providers/reactQueryProvider";
import UserProvider from "@/providers/providerUser";

const bondoni_nova = Bodoni_Moda({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bondoni-nova",
});

const tenor_sans = Tenor_Sans({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-tenor-sans",
});

export const metadata: Metadata = {
  title: "Open Fashion",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${bondoni_nova.variable} ${tenor_sans.variable} max-w-[25rem] mx-auto border-x-2 border-black/20 text-black `}
      >
        <ProviderNextAuth>
          <ReactQueryProvider>
            <UserProvider>
              <HeaderComponent />
              <ToasterContext />
              {children}
              <div id="modal-root" />
              <FooterComponent />
            </UserProvider>
          </ReactQueryProvider>
        </ProviderNextAuth>
      </body>
    </html>
  );
}
